//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Theater.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enployment
    {
        public int EnploymentID { get; set; }
        public int ActorID { get; set; }
        public int PerformanceID { get; set; }
        public string Role { get; set; }
        public string Cost { get; set; }
    
        public virtual Actor Actor { get; set; }
        public virtual Performance Performance { get; set; }
    }
}
